// Set the pixel color to an interesting procedural color generated by mixing
// and filtering Perlin noise of different frequencies.
//
// Uniforms:
uniform mat4 view;
uniform mat4 proj;
uniform float animation_seconds;
uniform bool is_moon;
// Inputs:
in vec3 sphere_fs_in;
in vec3 normal_fs_in;
in vec4 pos_fs_in; 
in vec4 view_pos_fs_in; 
// Outputs:
out vec3 color;

// expects: blinn_phong, perlin_noise
void main()
{
  /////////////////////////////////////////////////////////////////////////////
  // Reference: Textbook Chapter 11.5.3 (Turbulence)
  
  // Calculate where the light is
  float theta = 0.25 * M_PI * animation_seconds;
  vec4 light = view * vec4(4*cos(theta), 4, 4*sin(theta), 0.75);
  
  // Blinn Phong parameters
  vec3 ka, ks, kd;
  float p;
  if(is_moon){
	  ka = vec3(0.1, 0.1, 0.1);
	  ks = vec3(0.8, 0.8, 0.8);
	  kd = vec3(0.85, 0.85, 0.85);
	  p = 1000;
  }else{
	  ka = vec3(0.1, 0.1, 0.1);
	  ks = vec3(0.8, 0.8, 0.8);
	  kd = vec3(0.20, 0.30, 0.85);
	  p = 500;
  }

  vec3 n = normalize(normal_fs_in); // Eye is at (0,0,0)
  vec3 v = -normalize(view_pos_fs_in.xyz); // from a point on surface to the eye
  vec3 l = normalize(light.xyz - view_pos_fs_in.xyz); // from a point on surface to the light

  float obj_factor, k;
  if (is_moon){
	  obj_factor = 15;
	  k = 1.5; // density factor
  }else{
	  obj_factor = 30;
	  k = 3.0;
  }
  float noise = sqrt(abs(1 + sin(sphere_fs_in.x + obj_factor * perlin_noise(k * sphere_fs_in))/5));
  
  color = blinn_phong(ka, noise * kd, ks, p, n, v, l);
  /////////////////////////////////////////////////////////////////////////////
}
